/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bssCrowdSaleSol from "./BSSCrowdSale.sol";
export type { bssCrowdSaleSol };
export type { BSSToken } from "./BSSToken";
export type { USDT } from "./USDT";
export type { Vault } from "./Vault";
